In [1]:
import numpy as np
from neutral_network import Neural_Network

In [2]:
zero = [
  0, 1, 1, 0,
  1, 0, 0, 1,
  1, 0, 0, 1,
  1, 0, 0, 1,
  0, 1, 1, 0
]

one = [
  0, 0, 1, 0,
  0, 0, 1, 0,
  0, 0, 1, 0,
  0, 0, 1, 0,
  0, 0, 1, 0
]

two = [
  0, 1, 1, 0,
  1, 0, 0, 1,
  0, 0, 1, 0,
  0, 1, 0, 0,
  1, 1, 1, 1
]

three = [
  1, 1, 1, 1,
  0, 0, 0, 1,
  0, 1, 1, 1,
  0, 0, 0, 1,
  1, 1, 1, 1
]


predict = two

In [3]:
X = np.array((zero, one, two, three), dtype=float)
y = np.array(([0], [1], [2], [3]), dtype=float)
xPredicted = np.array((predict), dtype=float)

In [4]:
# scale units
y = y/3 # max test score is 100

In [6]:
NN = Neural_Network()
for i in range(100): # trains the NN 100,000 times
  print ("#" + str(i) + "\n")
  print ("Input: \n" + str(X))
  print ("Actual Output: \n" + str(y*3))
  print ("Predicted Output: \n" + str(NN.forward(X)*3))
  print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss
  print ("\n")
  NN.train(X, y)

NN.predict(xPredicted)

#0

Input: 
[[0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [2.]
 [3.]]
Predicted Output: 
[[2.81055793]
 [2.8796238 ]
 [2.80026928]
 [2.89552269]]
Loss: 
0.33565466468416005


#1

Input: 
[[0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [2.]
 [3.]]
Predicted Output: 
[[2.63153759]
 [2.80148679]
 [2.60302072]
 [2.82402986]]
Loss: 
0.29347067362677315


#2

Input: 
[[0. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0.]
 [0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0.

In [21]:
NN = Neural_Network()
o = NN.forward(X)
print(o)
print(y)

[[0.03175113]
 [0.02202631]
 [0.00291963]
 [0.01587725]]
[[0.        ]
 [0.33333333]
 [0.66666667]
 [1.        ]]


In [22]:
y-o

array([[-0.03175113],
       [ 0.31130702],
       [ 0.66374703],
       [ 0.98412275]])

In [23]:
NN.sigmoidPrime(o)

array([[0.030743  ],
       [0.02154115],
       [0.00291111],
       [0.01562516]])